### ISSUE TITLE
`OmegaConf.structured` does not parse dataclass attributes which are not typed

### ISSUE THREAD

**Issue by carmocca** [omry/omegaconf#489] opened 2021-01-22 17:28 UTC
**Describe the bug**

`OmegaConf.structured` does not parse dataclass attributes which are not typed

**To Reproduce**

```python
from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class Foo:
    z = "test"  # No type

x = Foo()
y = OmegaConf.structured(x)
print(y) # {}

@dataclass
class Foo:
    z: str = "test"  # Typed

x = Foo()
y = OmegaConf.structured(x)
print(y) # {'z': 'test'}
```

**Expected behavior**
Both print the same thing

**Alternatives**
It works if I the type is set to `Any`. However, for my use case, I want to allow users to pass their own dataclasses, so I don't want to force them to have their dataclasses completely typed.

**Additional context**
- OmegaConf version: 2.1.0.dev14
- Python version: 3.8.6
- Operating system : Linux Pop-os

**Comment by omry** [comment] 2021-01-22 18:02
Thanks for reporting.
This seems to be a problem in dataclasses and attr classes as well:
```
from dataclasses import dataclass, fields


@dataclass
class Foo:
    untyped = "foo"
    typed: str = "bar"


def print_fields(obj):
    obj_fields = fields(obj)
    for idx, field in enumerate(obj_fields):
        print(f"#{idx}: {field.name}")

print_fields(Foo)
```

[Per BDFL](https://github.com/ericvsmith/dataclasses/issues/2), this is by design.
without a type it's not a field.

If you can find a clean way to access these fields (that works for both dataclasses and attr classes and instances) I am open to a PR.

Closing, feel free to continue the discussion here though.

**Closed by omry** 2021-01-22 18:02 UTC
Labels: bug
