### ISSUE TITLE
Feature: Dict[int, ...] key type support

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#451] opened 2020-12-10 00:52 UTC
Hi Omry,

I noticed that a file in `tests/` checks to see that DictConfig raises a Key ValidationError when `OmegaConf.create({1: "a"})` is called with an `int` key type.

I've been using OmegaConf to validate/merge some yaml files according to a scheme defined by some dataclasses. I've run into the KeyValidationError when using dataclasses that have attributes typed as `Dict[int, float]`, or when calling `OmegaConf.load` on data that has int key types.

My feeling is that it would be fairly easy to add support for int key-type by adding an `elif` block to the `DictConfig._s_validate_and_normalize_key` method to handle the `int` case, and by changing several type signatures from `Union[str, Enum]` to `Union[str, int, Enum]` in the `dictconfig.py` and `_utils.py` files.

I'm wondering if support for int key types (and possibly other key types that are supported by YAML, such as float and bool) is a direction that you'd be interested in going.

**Comment by Jasha10** [comment] 2020-12-10 00:58
I have made a [commit](https://github.com/Jasha10/omegaconf/commit/1eadbdf8ff2dd11948902f35cc42cbd486167801) to a fork of the repository with the changes that I've mentioned above (though I haven't modified the test files to reflect the changed requirements). I can update the tests and submit a PR if you're interested.

**Comment by omry** [comment] 2020-12-10 02:47
Hi @Jasha10.
This is a duplicate of #149, adding such support will indeed be nice and is something I hope to get done for 2.1.
However, is a low level change that requires proper testing and documentation updates (including behavior with Structured Configs).
If you are interested in working on it file a pull request and I can provide feedback there.

Thanks!

(Closing this one because it's a duplicate).

**Closed by omry** 2020-12-10 02:47 UTC
