### ISSUE TITLE
Type validation for merging structured conf into non-structured conf

### ISSUE THREAD

**Issue by Jasha10** [omry/omegaconf#582] opened 2021-03-07 20:15 UTC
Normally, adding a new field to a structured config causes a `ConfigAttributeError`:
```python
$ cat tmp.py
from omegaconf import OmegaConf
from dataclasses import dataclass

@dataclass
class User:
    name: str = "bond"
    age: int = 7

if __name__ == "__main__":
    user = OmegaConf.structured(User)
    user.bla = 456
```
```bash
$ python tmp.py
Traceback (most recent call last):
    ...
omegaconf.errors.ConfigAttributeError: Key 'bla' not in 'User'
    full_key: bla
    object_type=User
```

And merging the new field into a structured config also causes an error:
```python
...
if __name__ == "__main__":
    user = OmegaConf.structured(User)
    other = {"bla": 456}
    OmegaConf.merge(User, other)
```
```bash
$ python tmp.py
Traceback (most recent call last):
    ...
omegaconf.errors.ConfigAttributeError: Key 'bla' not in 'User'
    full_key: bla
    object_type=User
```

But if the order of merge is reversed, the type validation is skipped:
```python
...
if __name__ == "__main__":
    user = OmegaConf.structured(User)
    other = {"bla": 456}
    cfg = OmegaConf.merge(other, user)
    print("OBJECT_TYPE:", cfg._metadata.object_type)
    print("CONFIG:\n" + OmegaConf.to_yaml(cfg))
```
```bash
$ python tmp.py
OBJECT_TYPE: <class '__main__.User'>
CONFIG:
bla: 456
name: bond
age: 7
```
No error has been raised, and a new field (outside of the `User` schema) has been added to the structured config.

**Expected behavior**
Type validation of structured configs should not depend on the order of merging.

**Additional context**
- OmegaConf version: 2.1.0dev20
- Python version: CPython 3.9.1
- Operating system : MacOS

**Comment by Jasha10** [comment] 2021-03-07 20:27
This has implications for using a schema in a Hydra defaults list. For example, in [Validating against a schema in the same config group](https://hydra.cc/docs/next/tutorials/structured_config/schema#validating-against-a-schema-in-the-same-config-group), there is the following example:
```yaml
# config.yaml
defaults:
  - base_config
  - db: mysql
```

If the order is reversed like this:
```yaml
defaults:
  - db: mysql
  - base_config
```
then there will not be proper type validation.

**Comment by omry** [comment] 2021-03-09 19:06
This is an issue I was aware of.
We can try to fix it, but there could be some unexpected consequences (I think if the fix passes the Hydra tests it should be good).

> This has implications for using a schema in a Hydra defaults list. For example, in Validating against a schema in the same config group, there is the following example:

Do you have a more realistic example where this would cause an issue? In your example switching the order is wrong: You want to specialize the base_config, not the other way around.

**Comment by Jasha10** [comment] 2021-03-10 08:54
> Do you have a more realistic example where this would cause an issue? In your example switching the order is wrong: You want to specialize the base_config, not the other way around.

I could not find a more realistic example.
I was playing with the following
```python
from omegaconf import OmegaConf
from tests import Plugin, ConcretePlugin
cfg = OmegaConf.merge(ConcretePlugin, Plugin)
```
and was surprised when I got a ValidationError :)

**Comment by omry** [comment] 2021-06-05 00:09
I think we have a separate discussion about this topic again recently and we decided that this as intended.
Closing, let me know if you disagree.

**Closed by omry** 2021-06-05 00:09 UTC
Labels: bug
