### ISSUE TITLE
Be able to add field to dict types unless the node itself is marked as structured mode

### ISSUE THREAD

**Issue by jieru-hu** [omry/omegaconf#461] opened 2020-12-17 02:27 UTC
Minimal repro
```python
from dataclasses import dataclass, field
from omegaconf import OmegaConf
from typing import Dict


@dataclass
class SimpleTypes:
    num: int = 10
    pi: float = 3.1415
    is_awesome: bool = True
    dictionary: Dict[str, str] = field(default_factory=dict)


cfg = OmegaConf.structured({"root" : SimpleTypes})
OmegaConf.set_struct(cfg, True)
cfg.root.dictionary.foo = "bar"
```

It might make sense to allow adding the key to the `Dict` instead (unless the Dict is explicit set to be struct)

**Comment by omry** [comment] 2020-12-17 04:26
Thanks for reporting.
It's worth considering to change the behavior for Dict fields to allow addition of new fields even if they have a parent that is marked as struct.

**Comment by omry** [comment] 2021-02-17 00:11
From the perspective of OmegaConf, this does not make sense.
If a top level config node has the struct flag set, then by design it applies to all sub nodes.

This can probably be fixed in Hydra by not setting struct mode if the top level config is a Structured Config.
In that case, it's a reasonable assumption that the entire config is typed and struct mode is not providing any value.

**Comment by omry** [comment] 2021-02-25 01:16
Fix in Hydra: https://github.com/facebookresearch/hydra/pull/1422/

**Comment by omry** [comment] 2021-03-07 04:58
Turns out the fix in Hydra is causing some [issues](https://github.com/facebookresearch/hydra/issues/1457), so I decided to revisit this and handle it in OmegaConf after all.
The current implementation I have is to set the struct flag to False when creating DictConfig nodes annotated as Dict[K, V].

**Comment by omry** [comment] 2021-03-09 21:01
#588 is introducing a new internal concept that can will help here.

**Closed by omry** 2021-03-09 21:01 UTC
Labels: In progress, enhancement

**Comment by omry** [comment] 2021-03-10 01:51
After going back and forth I finally decided that the current behavior makes sense, unconditionally.
There are use cases where one wants to have the struct flag apply to a dict and others where one does not.
The default choice for Hydra to set the config root to strut mode makes sense in general. If someone wants to add new fields to nested dicts they should use + as they did with Hydra 1.0.
