### ISSUE TITLE
Perform mathematical operations with interpolated variables.

### ISSUE THREAD

**Issue by diegovalenzuelaiturra** [omry/omegaconf#437] opened 2020-11-09 20:44 UTC
## idea

I would like to perform math operations that involve more than one interpolated (probably unresolved) numerical variable, when using structured configurations.

Considering the following example :

## imports

```python3
from typing import Any, Optional

from dataclasses import dataclass
from omegaconf import OmegaConf, MISSING, II
```

##  dataclasses

```python3
@dataclass
class R:
    p: int = MISSING
    q: int = MISSING

@dataclass
class S:
    a: int = MISSING
    b: int = MISSING
    c: int = MISSING

@dataclass
class T:
    r: R = MISSING
    s: S = MISSING
```

## example

I'd like to do something like the following :

```python3
rho: float = 0.5

t = T(
    r=R(
        p=128,
        q=100
    ),
    s=S(
        a = II("r.p") - II("r.q"),
        b = - II("r.q"),
        c = int( rho * II("s.a") * II("s.b") )
    )
)
```

And that the mathematical operations will be executed as follows, once the interpolated variables have been resolved

```python3
t = T(
    r=R(
        p=128,
        q=100
    ),
    s=S(
        a = 128 - 100,
        b = - 100,
        c = int( 0.5 * (128 - 100) * (-100) )
    )
)
```

To culminate having the following configuration

```yaml
r:
  p: 128
  q: 100
s:
  a: 28
  b: -100
  c: -1400
```

**Comment by omry** [comment] 2020-11-10 00:06
Thanks for the suggestion, this is a duplicate of #91.

**Closed by omry** 2020-11-10 00:06 UTC
