### ISSUE TITLE
[bug] Nested interpolations don't work

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#212] opened 2020-04-18 19:19 UTC
Nested interpolations only resolve inner level interpolations.

```py
a = OmegaConf.create({"a": "${hello:${default_hello:}}"})
OmegaConf.register_resolver("hello", lambda x: x)
OmegaConf.register_resolver("default_hello", lambda: 1)
print(a.a) # prints ${hello:1}
```

Expected: 1

The major issue this causes is when I want to register a resolver for an environmental variable's default value.

Workaround:
Register an overall resolver and resolve environment value yourself in it.

**Comment by omry** [comment] 2020-04-18 19:37
Duplicate of #100

**Closed by omry** 2020-04-18 19:37 UTC
