### ISSUE TITLE
how to assert omegaconf.listconfig.ListConfig is list

### ISSUE THREAD

**Issue by yuwl798180** [omry/omegaconf#51] opened 2019-10-27 12:01 UTC
when I use the cfg's property such as cfg.kernel_sizes, I what to compare cfg.kernel_sizes with list, tuple, or int

my code is that:

```python
if isinstance(cfg.kernel_sizes, (list, tuple, int)):
    ...
```

but the type(cfg.kernel_sizes) is omegaconf.listconfig.ListConfig, not list, so I can't get the true judgement

I want to know how to make the types become list, dict and  other standard types

**Comment by swist** [comment] 2019-10-28 11:18
Currently the configs don't inherit from primitives, but they expose the underlying primitive in a `content` field. 
So your snippet becomes:
```python
if isinstance(cfg.kernel_sizes.content, (list, tuple, int)):
    ...
```

**Comment by omry** [comment] 2019-10-28 11:32
No, do not interact with internal members.
You can test if the object is ListConfig or DictConfig.
If you need an actual primitive container you can convert with to_container()

**Comment by omry** [comment] 2019-10-28 11:39
on a laptop now:
1. OmegaConf may look like a list/dict, but it's not.
if you need to convert it to such use cfg.to_container(resolve=True)
(by default resolve is not True, which means you get fields like ${foo} as is.

Closing, this is not a bug.

**Closed by omry** 2019-10-28 11:39 UTC

**Comment by cipri-tom** [comment] 2023-05-12 09:35
@omry may I ask why this is not a bug ?
If a OmegaConfig looks like a dict, and it supports dict methods, like `.items()`, then it should return true to `isinstance(conf, dict)`. Why do we need non-standard `is_dict()` method when an elegant and native way exists in Python ?
Thank you !

**Comment by omry** [comment] 2023-05-12 09:56
This is a design choice to not extend Python primitive containers.
This design choice is set and will never change.

**Comment by omry** [comment] 2023-05-12 18:22
Python primitives are not designed to be extended. While it can work, it's risky on several levels:
1. Not having full control over your implementation (subclass implementation can change across different Python versions), resulting on some nasty bugs.
2. Potentially breaking Python optimizations not expecting userland subclasses of native containers.

At this point, even if I did want to change that, the cost is too high because code handling, for example - both `list` and `ListConfig` would break.
