### ISSUE TITLE
anchors and aliases from multiple yaml documents

### ISSUE THREAD

**Issue by Lads0909** [omry/omegaconf#785] opened 2021-09-06 12:45 UTC
Is there an implementation available from the omegaconf package in which I can use aliases and anchors from different yaml documents.

**document1.yml:**
Parameter: &Anchor ParameterValue

**document2.yml:**
Test_document2:
  Parameter_document1: *Anchor

**document3.yml:**
Test_document3:
  Parameter_document1: *Anchor

after loading and merging above files, I should get a config_obj which contains below parameters:

Parameter: ParameterValue

Test_document2:
  Parameter_of_document1: ParameterValue

Test_document3:
  Parameter_of_document1: ParameterValue

If I try this with a "normal" merge and load I get the error:
    raise ComposerError(None, None, "found undefined alias %r"

Can you please support me with any hint?

Thanks

**Comment by Jasha10** [comment] 2021-09-07 17:57
I believe that the issue is that yaml anchors are resolved by `pyyaml`. This happens before the OmegaConf object is created.
See my comment on #787 for an idea of how to do this using OmegaConf's [interpolation](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#variable-interpolation) feature.

**Comment by omry** [comment] 2021-09-07 19:33
Yes, what Jasha said. Use interpolations instead.

**Closed by omry** 2021-09-07 19:33 UTC
