### ISSUE TITLE
Parsing datetime from YAML config

### ISSUE THREAD

**Issue by sxooler** [omry/omegaconf#446] opened 2020-12-01 16:09 UTC
**Describe the bug**
I'm not sure whether this is a bug or a feature but OmegaConf parses all datetime in YAML config as string unlike [PyYAML](https://pyyaml.org/) package. Is there reason for different behavior? And if so is there a way how to parse datetime field with OmegaConf smartly?

**To Reproduce**
```yaml
# test.yaml
date_str: '2020-12-01'
date: 2020-12-01
```

When I use PyYAML and do following, it outputs what I expect:
```python
import yaml

with open("test.yaml") as f:
    conf = yaml.safe_load(f)

print(conf)
# {'date_str': '2020-12-01', 'date': datetime.date(2020, 12, 1)}
```

When I use OmegaConf, both values are of string type:
```python
from omegaconf import OmegaConf

conf = OmegaConf.load("test.yaml")
print(conf)
# {'date_str': '2020-12-01', 'date': '2020-12-01'}
```

**Expected behavior**
I would expect to get the same behaviour as with PyYAML or some way how to configure that.

**Additional context**
- [x] OmegaConf version: 2.0.5
- [x] Python version: 3.7.6

**Comment by omry** [comment] 2020-12-01 17:30
This is intentional. datetime is not a supported primitive type in OmegaConf and there are no plans to support it.
I suggest that you do the datetime parsing when you consume the field.

If you really want the returned field to be a datetime object, you can achieve that with custom resolvers:
```python
from omegaconf import OmegaConf
from datetime import datetime

OmegaConf.register_resolver("my_datetime", datetime.fromisoformat)
cfg = OmegaConf.create({"foo": "${my_datetime:2011-11-04}"})
print("type:", type(cfg.foo), "value:", cfg.foo)
```
```
$ python 1.py 
type: <class 'datetime.datetime'> value: 2011-11-04 00:00:00
```

**Comment by omry** [comment] 2020-12-01 17:31
Closing as this is not a bug.

**Closed by omry** 2020-12-01 17:31 UTC
Labels: bug

**Comment by sxooler** [comment] 2020-12-01 17:56
Thank you! I was expecting that it should be supported somehow especially when it's included in widely used PyYAML library. The workaround with custom resolver is not what I was looking for (you have to use `${}` notation) but at least it's working.

My main concern is regarding Hydra package which you know very well, as it seems I cannot properly use datetime format in configs (even with dataclass validation) but my feeling was it's mainly because OmegaConf so I raised this issue. I will probably raise it there when the intention for supported datetime is not planned here.

Thank you.

**Comment by omry** [comment] 2020-12-01 18:43
While OmegaConf is currently using PyYAML it is not guaranteed to support all of PyYAML's features.

Hydra is using OmegaConf for things like Structured Configs so this is the right place to discuss that limitaion.
Each additional primitive type has a significant cost in tests and surface area. In addition, this would be a breaking change for people that are already passing date strings and are expecting them to be strings.

**Comment by sxooler** [comment] 2021-06-15 08:28
I'm getting back to you. This is still an issue for me, I guess nothing has changed from your point of view, that there is no plan to support datetimes, right?

My major concern is that I'm using some other source of data/configs and some of them are coming in datetime format. When I want to add that to omegaconf Dict, it will fail. If I understand this correctly, your approach would be to register also something like `omegaconf_compatible` function that would turn this into the value that will be understandable by custom resolver?

Example:
```python
conf: DictConfig = ...  # somehow created config using omegaconf

conf["custom_config"] = custom_config  # custom config is python dict with some datetime field as well, this will fail

OmegaConf.save(conf, path, resolve=True)
# later, e.g. in different script
conf = OmegaConf.load(path)
```

Is there any better way:
```python
conf: DictConfig = ...  # somehow created config using omegaconf

custom_config = convert_datetimes(custom_config)
conf["custom_config"] = custom_config  # custom config compatible with omegaconf

OmegaConf.save(conf, path, resolve=True)
# later, e.g. in different script
OmegaConf.register_resolver("my_datetime", datetime.fromisoformat)
conf = OmegaConf.load(path)
```
where `convert_datetimes` function would iterate over dictionary, and when datetime detected it would call something like `f"${{my_datetime:{datetime_value.isoformat()}}}"`.

Or is there any way how to specify some "type_converter" (similarly like custom resolver)? Or would it be possible to add something like that?

What I mean is that I would like to enable both ways (to and from) for omegaconf and datetime. "from" part is easily done by registering new resolver, but "to" has to be done by another function. I would like to keep both functions somehow close (lets say internal yaml format for datetime will be string here, and in omegaconf I could register both methods, here e.g. fromisofromat and toisoformat, together, so it would be defined in one place).

**Comment by Jasha10** [comment] 2021-06-15 22:48
Hi @sxooler,

Here is a hack that might work for your use-case. This solution uses several undocumented APIs and might not be compatible with future versions of OmegaConf.

```python
from omegaconf import OmegaConf, DictConfig, ListConfig
from typing import Union
from datetime import datetime

external_data = dict(
    t=datetime.now(),
    other1=123,
    other2="abc",
)


# The 'allow_objects' flag allows unsupported types in an OmegaConf object. Undocumented API!
cfg = OmegaConf.create({}, flags={"allow_objects": True})
cfg.ext = external_data  # does not fail because 'allow_objects' is set.
print(
    cfg.ext
)  # prints {'t': datetime.datetime(2021, 6, 15, 17, 43, 43, 29289), 'other1': 123, 'other2': 'abc'}
print(type(cfg.ext.t))  # prints <class 'datetime.datetime'>
print(cfg._get_flag("allow_objects"))  # prints True

OmegaConf.save(cfg, "tmp.pkl")
cfg2 = OmegaConf.load("tmp.pkl")

# It seems that datetime objects are converted to `str` by OmegaConf's save/load
print(
    cfg2.ext
)  # prints {'t': '2021-06-15 17:43:43.029289', 'other1': 123, 'other2': 'abc'}
print(type(cfg2.ext.t))  # prints <class 'str'>
print(cfg2._get_flag("allow_objects"))  # prints None

# On the loaded config, we set the "allow_objects" flag before converting to datetime.
cfg2._set_flag("allow_objects", True)
print(cfg2._get_flag("allow_objects"))  # prints True
# _set_flag and _get_flag are undocumented! Might not be forward-compatible.

# Now loop over all values in the config and convert to datetime
def convert_to_datetime(_cfg: Union[DictConfig, ListConfig]) -> None:
    """
    Recursively traverse OmegaConf object,
    converting strings to datetime when possible.
    """
    # The below lines of code for looping over a DictConfig/ListConfig are
    # borrowed from OmegaConf PR #719.
    itr: Iterable[Any]
    if isinstance(_cfg, ListConfig):
        itr = range(len(_cfg))
    else:
        itr = _cfg

    for key in itr:
        if OmegaConf.is_missing(_cfg, key):
            continue
        elif OmegaConf.is_config(_cfg[key]):
            convert_to_datetime(_cfg[key])
        elif isinstance(_cfg[key], str):
            try:
                _cfg[key] = datetime.fromisoformat(_cfg[key])
            except ValueError:
                pass


convert_to_datetime(cfg2)
print(cfg2.ext)  # prints {'t': datetime.datetime(2021, 6, 15, 17, 43, 43, 29289), 'other1': 123, 'other2': 'abc'}
print(type(cfg2.ext.t))  # prints <class 'datetime.datetime'>
```

**Comment by sxooler** [comment] 2021-06-18 07:35
Hi @Jasha10,

thank you for sharing this approach. I didn't know about `allow_objects` flag. Is that part of public API or is it recommended not to use it? @omry: Do you have any comment on using this flag?

Regarding your loading approach with try/except block is something I do not like because it does not distinguish the original types. Lets say the original config would be something like `{'start_time': datetime.datetime(2021, 6, 15, 17, 43, 43, 29289), 'start_time_str': '2021-06-15 17:43:43.029289'}`, than you would store both of them as string and both would be loaded as datetime object when trying `fromisoformat` method.

I would like to use some approach that would keep those types consistent (before saving vs. after loading). Otherwise it's nice solution, thanks!

**Comment by Jasha10** [comment] 2021-06-18 20:12
The `allow_objects` flag is not documented, so it's not part of the public API. All I can say is to use it "at your own risk" :)

I've just realized that the filename `"tmp.pkl"` from my example above is misleading -- the contents of the serialized file do not appear to be in a binary format (as one would expect using the python `pickle` library).

Here is the file that was saved to disk:
```yaml
ext:
  t: 2021-06-15 17:43:43.029289
  other1: 123
  other2: abc
```

> it does not distinguish the original types.

Hmm. In this case, you could prefix the converted values with a special string of your choosing, so that they are distinguishable from other values from the external data. Here is an example routine:
- before loading the external data into OmegaConf, traverse the external data structure and convert all the `datetime` instances to some format that OmegaConf supports. For example, convert `datetime.datetime(2021, 6, 15, 17, 43, 43, 29289)` into `'my_datetime_value_prefix_2021-06-15 17:43:43.029289'`.
- When reading the serialized data from disk, you can convert back to datetime using something like this:
```python
if isinstance(value, str) and value.startswith("my_datetime_value_prefix_"):
    converted = datetime.fromisoformat(value.removeprefix("my_datetime_value_prefix_"))
```

**Comment by Jasha10** [comment] 2021-06-18 21:00
> I've just realized that the filename `"tmp.pkl"` from my example above is misleading

I was able to simplify the example by using pickle instead of OmegaConf.save:
```python
from omegaconf import OmegaConf, DictConfig, ListConfig
from typing import Union
import pickle
from datetime import datetime

external_data = dict(
    t=datetime.now(),
    other1=123,
    other2="abc",
)


# The 'allow_objects' flag allows unsupported types in an OmegaConf object. Undocumented API!
cfg = OmegaConf.create({}, flags={"allow_objects": True})
cfg.ext = external_data  # does not fail because 'allow_objects' is set.
print(cfg.ext)  # prints {'t': datetime.datetime(2021, 6, 15, 17, 43, 43, 29289), 'other1': 123, 'other2': 'abc'}
print(type(cfg.ext.t))  # prints <class 'datetime.datetime'>
print(cfg._get_flag("allow_objects"))  # prints True

pickle.dump(cfg, open("tmp.pkl", "wb"))
cfg2 = pickle.load(open("tmp.pkl", "rb"))
# OmegaConf.save(cfg, "tmp.pkl")
# cfg2 = OmegaConf.load("tmp.pkl")

print(cfg2.ext)  # prints {'t': '2021-06-15 17:43:43.029289', 'other1': 123, 'other2': 'abc'}
print(type(cfg2.ext.t))  # prints <class 'datetime.datetime'>
print(cfg2._get_flag("allow_objects"))  # prints True
```

**Comment by omry** [comment] 2021-06-18 23:08
> thank you for sharing this approach. I didn't know about allow_objects flag. Is that part of public API or is it recommended not to use it? @omry: Do you have any comment on using this flag?

This is not officially supported and we can't commit it would continue to work in future versions, or that it will work correctly with all existing features in OmegaConf.

Taking a step back:

Changing the interpretation of a date line string loaded in the config from a string to a datetime object is a breaking change.
In addition, adding new supported types is a very big deal that requires a lot of additional tests, which would need to be maintained for ever. (for context, OmegaConf now have over 4500 tests).

As I said, I am not planning to support it.
You are free to fork the project and add support for whatever you want in your own version.
