### ISSUE TITLE
[bug] hasattr on missing nested attributes should return False

### ISSUE THREAD

**Issue by apsdehal** [omry/omegaconf#173] opened 2020-03-23 08:16 UTC
Minimal example to reproduce the bug:
```
import omegaconf
a= omegaconf.OmegaConf.create({"a": {"b": [1, 2], "c": "abc"}})
print(hasattr(a, "d"))
```
prints `True`. OmegaConf version: `2.0.0rc15`

**Comment by omry** [comment] 2020-03-24 23:36
This is impossible to fix as far as I can tell:
hasattr relies on AttributeError, but by design `a.d` returns None when not in struct mode so it cannot throw an AttributeError.

Closing this, but feel free to discuss further here on in a message.

**Closed by omry** 2020-03-24 23:36 UTC
Labels: bug
